[project]
name = "repo-redirect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.136.1",
    "pytest>=9.0.3",
]

[dependency-groups]
dev = [
    "prek>=0.4.1",
    "ruff>=0.15.14",
    "ty>=0.0.38",
    "zizmor>=1.25.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.fastapi]
entrypoint = "src.app.main:app"
